version: '3.8'

services:
  copilot-api:
    image: kofekofe/copilot-api:latest
    ports:
      - '5262:5262'
    environment:
      ConnectionStrings__NpgSql: '${NpgSql}'
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.api_allowed == true
        preferences:
          - spread: node.labels.api_primary
    networks:
      - copilot_net

  copilot-admin:
    image: kofekofe/copilot-admin:latest
    ports:
      - '80:80'
    environment:
      API_URL: 'http://165.227.154.109:5462'
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.admin_allowed == true
        preferences:
          - spread: node.labels.admin_primary
    networks:
      - copilot_net

networks:
  copilot_net:
    driver: overlay