version: '3.8'

services:
  copilot-api:
    image: kofekofe/copilot-api:latest
    ports:
      - "5262:8080"
    environment:
      ConnectionStrings__NpgSql: ${NpgSql}
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.api_primary == true    # only back/front primaries
          - node.labels.backup != true         # exclude backup when primary available
    networks:
      - copilot_net

  copilot-admin:
    image: kofekofe/copilot-admin:latest
    ports:
      - "80:80"
    environment:
      - API_URL=http://165.227.154.109:5462
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
        - node.labels.admin_primary == true  # only front primaries
        - node.labels.backup != true         # exclude backup when primary available
    networks:
      - copilot_net

networks:
  copilot_net:
    driver: overlay
